apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::346204448127:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-3I8PUM455AVF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::346204448127:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-10T01:12:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1523"
  uid: e3f8173a-b9ee-4311-afc2-1c9981c42608
